### ISSUE TITLE
It shows the Terminal fontvalue incorrectly

### ISSUE THREAD

**Issue by og900aero** [fastfetch-cli/fastfetch#631]
The last fastfetsch doesnt know Alacritty new config file format. Alacritty has new config format "toml" since Alacritty 0.13

Old Alacritty version use yaml config file:
```
font:
 normal:
   family: IosevkaTerm Nerd Font Mono
 size: 9.0
```

New Alacritty use toml config file:
```
[font]
size = 9.0
[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "regular"
```

**Comment by CarterLi** [comment]
Please test it

**Comment by seriousm4x** [comment]
While @og900aero's toml works, it is also possible to write the toml in a different way:

```toml
[font]
size = 12.0
normal = {family = "FiraCode Nerd Font"}
```

Which will fail to recognize the font and result in `Terminal Font: alacritty (12.0pt)`
